### ISSUE TITLE
json data

### ISSUE THREAD

**Issue by mourareaupro** [palmans/laravel-openfoodfacts#1]
Hello, 

I would like to use $data in my front end and retrieve all the data

`public function findFood($code){

        $data = \Palmans\LaravelOpenFoodFacts\Facades\OpenFoodFacts::barcode($code);
        
        return response()->json([
            "data" => $data
        ], 200);
    }`

I get an empty data{}

How could i display the whole array ? thanks i advance

**Comment by epalmans** [comment]
you could cast the result to an array and grab the first element. Or even easier to wrap $data in a reset() directly:

```
    $data = \Palmans\LaravelOpenFoodFacts\Facades\OpenFoodFacts::barcode($code);
    
    return response()->json([
        "data" => reset($data),
    ], 200);
```

**Comment by mourareaupro** [comment]
> you could cast the result to an array and grab the first element. Or even easier to wrap $data in a reset() directly:
> 
> ```
>     $data = \Palmans\LaravelOpenFoodFacts\Facades\OpenFoodFacts::barcode($code);
>     
>     return response()->json([
>         "data" => reset($data),
>     ], 200);
> ```

thanks :))))

**Comment by mourareaupro** [comment]
> you could cast the result to an array and grab the first element. Or even easier to wrap $data in a reset() directly:
> 
> ```
>     $data = \Palmans\LaravelOpenFoodFacts\Facades\OpenFoodFacts::barcode($code);
>     
>     return response()->json([
>         "data" => reset($data),
>     ], 200);
> ```

One last question when i try collections i get empty objects : 



data: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},…]
[0 … 99]
[100 … 199]
[200 … 299]
200: {}
201: {}
202: {}
203: {}
204: {}
205: {}
206: {}
207: {}



```
public function findFood($query){

        $data = \Palmans\LaravelOpenFoodFacts\Facades\OpenFoodFacts::find($query);


        return response()->json([
            "data" => reset($data),
        ], 200);
    }
```

**Comment by epalmans** [comment]
you could do the same for the collection items:

```
    $collection = OpenFoodFacts::find('Coca Cola Zero')->map(function ($document) {
        return reset($document);
    });
```

**Comment by mourareaupro** [comment]
> you could do the same for the collection items:
> 
> ```
>     $collection = OpenFoodFacts::find('Coca Cola Zero')->map(function ($document) {
>         return reset($document);
>     });
> ```

works like a charm :) 

another thing when i'm looking for another product like "pâtes" i'm getting this : {message: "ERROR: 30287 results found, while buffer limited to 1000. Please narrow your search.",…}
message: "ERROR: 30287 results found, while buffer limited to 1000. Please narrow your search."
exception: "Exception"
file: "/var/www/vendor/palmans/laravel-openfoodfacts/src/OpenFoodFacts.php"
line: 49
trace: [{file: "/var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php", line: 261,…},…]

when i update the buffer size it's take so many times, so you have a trick or tips to resovle this  ? should i add more filters to my form ? 

One last thing, this warpper can add a product ?

**Comment by epalmans** [comment]
the message means that there are too many results for the given search term.
You could bypass this limit by setting a parameter from the configuration (config\openfoodfacts.php). You may install the default config. with this command: ```php artisan vendor:publish --provider="Palmans\LaravelOpenFoodFacts\OpenFoodFactsServiceProvider" --tag="config"```

 > One last thing, this warpper can add a product ?

You could do so by calling the underlying api directly: ```OpenFoodFacts::addNewProduct(array $postData)```. Untested though. See documentation: https://en.wiki.openfoodfacts.org/API/Write#Posting_a_new_product

**Comment by mourareaupro** [comment]
works :) many thanks will take a look on it and test :) thanks again

**Comment by epalmans** [comment]
happy to help

**Comment by epalmans** [comment]
This issue made me aware that it actually makes more sense to return arrays instead of \OpenFoodFacts\Document instances. I've reflected that change in a new 2.0 release of the package.

The above solution still works on the 1.x release, but you could upgrade if you would want to:
```
composer require palmans/laravel-openfoodfacts
```

...after that, you could then simply do:
```php
return response()->json([
    'data' => OpenFoodFacts::barcode($barcode),
]);
```
or
```php
return response()->json([
    'matches' => OpenFoodFacts::find('Coca Cola Zero'),
]);
```

**Comment by mourareaupro** [comment]
> This issue made me aware that it actually makes more sense to return arrays instead of \OpenFoodFacts\Document instances. I've reflected that change in a new 2.0 release of the package.
> 
> The above solution still works on the 1.x release, but you could upgrade if you would want to:
> 
> ```
> composer require palmans/laravel-openfoodfacts
> ```
> 
> ...after that, you could then simply do:
> 
> ```
> return response()->json([
>     'data' => OpenFoodFacts::barcode($barcode),
> ]);
> ```
> 
> or
> 
> ```
> return response()->json([
>     'matches' => OpenFoodFacts::find('Coca Cola Zero'),
> ]);
> ```

that's mutch better in my option, i was a little bit confuse with the Document instance, thanks for the improvement :)
