### ISSUE TITLE
Get categories

### ISSUE THREAD

**Issue by mourareaupro** [palmans/laravel-openfoodfacts#2]
I need to make a search query in order the get an existing catergory on the api , any method on the class to achieve this ? 

many thanks in advance

**Comment by epalmans** [comment]
not sure what you mean. Could you elaborate / add a code snippet ?

Note that not all product are categorized, but does that have been include a 'categories_tags' that returns an array:

```php
$product = OpenFoodFacts::barcode('5000171010025');
$product['categories_tags'];

``` 
returns:
```
=> [
     "en:canned-foods",
     "en:seafood",
     "en:fishes",
     "en:canned-fishes",
     "en:salmons",
     "en:canned-salmons",
   ]
```

list of all categories can be found here: https://world.openfoodfacts.org/categories.json

**Comment by mourareaupro** [comment]
I would like to perform a search query for categories list only (https://fr.openfoodfacts.org/categories.json) 

Actualy whe can perform and get only products, is it possible ?

**Comment by mourareaupro** [comment]
For exemple OpenFoodFacts::category('brevages'); and get the list inside the category, possible ?

**Comment by epalmans** [comment]
unfortunately this is not implement in the API.
However, you can parse the json manually -> https://en.wiki.openfoodfacts.org/API/Read [for example ```https://fr-en.openfoodfacts.org/category/pizzas.json```]
