### ISSUE TITLE
Becoming the official laravel package

### ISSUE THREAD

**Issue by teolemon** [palmans/laravel-openfoodfacts#3]
Hi @palmans 
I was wondering if you were on the Open Food Facts slack (https://slack.openfoodfacts.org) on the #php channel.
It would be great to have an official Laravel package, and possibly mutualise code with the generic PHP repository.

**Comment by teolemon** [comment]
cc @epalmans

**Comment by epalmans** [comment]
just joined the Slack. Happy to discuss options

**Comment by epalmans** [comment]
Now an official package! See https://github.com/openfoodfacts/openfoodfacts-laravel  🎉 

Note: as a result this repo (palmans/laravel-openfoodfacts) will be abandoned in favour of the official one
